name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.8'
    - name: Display Python version
      run: python --version
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
      continue-on-error: true
    - name: List installed packages
      run: pip list
    - name: Run tests
      run: |
        which pytest
        pytest --version
        pytest
      continue-on-error: true
    - name: Check Docker installation
      run: docker --version
    - name: Build Docker image
      run: |
        docker build -t mlops_project .
      continue-on-error: true
    - name: Push to Docker Hub
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        echo "Attempting to log in to Docker Hub..."
        echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
        echo "Tagging Docker image..."
        docker tag mlops_project $DOCKER_USERNAME/mlops_project
        echo "Pushing Docker image..."
        docker push $DOCKER_USERNAME/mlops_project
      continue-on-error: true
